package routes

import (
	"github.com/gin-gonic/gin"

	_ "github.com/likid1412/address/docs" // generated by swag

	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware
)

// Init initializes the Gin router and sets up API routes for the application.
// It also serves Swagger documentation for API reference.
func Init() *gin.Engine {
	r := gin.Default()

	v1 := r.Group("/api/v1")
	address := v1.Group("/address")
	address.POST("upload", Upload)
	address.GET("retrieval/:filename", RetrievalAllInfo)

	// swagger
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}
